spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/quicktable_users
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

notification-service:
  url: http://localhost:3001

app:
  base-url: http://localhost:3000

logging:
  level:
    "[com.quicktable]": DEBUG
